### ISSUE TITLE
for TensorFlow version

### ISSUE THREAD

**Issue by 554327** [CarsonYang518/AAAI24-AES-AFG#1]
Hello, for the aes-afg, I would like to ask what is the version of TensorFlow, I can't find the version 2.15.0.

**Comment by CarsonYang518** [comment]
Please try to update the Python version to 3.11 for the installation of TensorFlow.

**Comment by 554327** [comment]
thanks. Do the other versions need to be change? such as Pytorch,scikit-learn.

**Comment by CarsonYang518** [comment]
No worries, I think other versions should be fine.

**Comment by 554327** [comment]
ok thanks
